[workspace]
members = [
    "rafx",
    "rafx-base",
    "rafx-api",
    "rafx-nodes",
    "rafx-visibility",
    "rafx-framework",
    "rafx-shader-processor",
    "rafx-assets",
    "demo",
    "demo/shaders",
    "demo/cli",
]

exclude = [

]

# Example of overriding a single crate. Doesn't affect dependencies though so it's of limited value
#[profile.dev.package.image]
#opt-level = 2

# Set the default for dependencies.
[profile.dev.package."*"]
opt-level = 2

# Set the settings for build scripts and proc-macros.
[profile.dev.build-override]
opt-level = 2

# Required for https://github.com/gltf-rs/gltf/pull/288
#[patch.crates-io]
#gltf = { path = "gltf" }

#[patch."https://github.com/aclysma/atelier-assets"]
#atelier-assets = { path = "atelier-assets" }
#atelier-cli = { path = "atelier-assets/cli" }
#atelier-assets = { git = "https://github.com/amethyst/atelier-assets.git" }
#atelier-cli = { git = "https://github.com/amethyst/atelier-assets.git" }

#[patch.crates-io]
#metal = { path = "../metal-rs" }
