[workspace]
members = [
    "renderer",
    "demo",
    "shader-processor"
]

exclude = [
    "atelier-assets",
    "gltf"
]

# Example of overriding a single crate. Doesn't affect dependencies though so it's of limited value
#[profile.dev.package.image]
#opt-level = 2

# Set the default for dependencies.
[profile.dev.package."*"]
opt-level = 2

# Set the settings for build scripts and proc-macros.
[profile.dev.build-override]
opt-level = 2

# Required for https://github.com/gltf-rs/gltf/pull/288
#[patch.crates-io]
#gltf = { path = "gltf" }

#[patch."https://github.com/aclysma/atelier-assets"]
#atelier-assets = { path = "atelier-assets" }
