[package]
name = "renderer"
version = "0.1.0"
authors = ["Philip Degarmo <aclysma@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = ">=0.30"
sdl2 = { version = ">=0.33" }

renderer-base = { path = "renderer-base" }
renderer-sdl2 = { path = "renderer-sdl2"}

log="0.4"

glam = "0.8.6"

legion = "0.2.1"

[dev-dependencies]
env_logger = "0.6"