[workspace]
members = [
    "renderer",
]

exclude = [
    "atelier-assets",
    "gltf"
]

[patch.crates-io]
gltf = { path = "gltf" }

[patch."https://github.com/amethyst/atelier-assets"]
atelier-assets = { path = "atelier-assets" }
