[package]
name = "shader-processor"
version = "0.1.0"
authors = ["Philip Degarmo <aclysma@gmail.com>"]
edition = "2018"

[dependencies]
fnv = "1.0"
structopt = "0.3"
spirv-reflect = "0.2"
shaderc = "0.6"

ron = "0.5"
serde = { version = "1.0", features = ["derive"] }
