[package]
name = "renderer"
version = "0.1.0"
authors = ["Philip Degarmo <aclysma@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = ">=0.30"
sdl2 = { version = ">=0.33" }
imgui = "0.3"
image = "0.23.3"

renderer-shell-vulkan = { path = "../renderer-shell-vulkan" }
renderer-shell-vulkan-sdl2 = { path = "../renderer-shell-vulkan-sdl2"}

renderer-base = { path = "../renderer-base" }
renderer-ext = { path = "../renderer-ext" }

log="0.4"
env_logger = "0.6"

glam = "0.8.6"

#legion = "0.2.1"
legion = { git = "https://github.com/TomGillen/legion.git" }
atelier-assets = { git = "https://github.com/amethyst/atelier-assets" }




structopt = "0.3"
serde = "1"
uuid = "0.8"
type-uuid = "0.1"
image2 = { version = "0.11", features = [ "ser" ] }
inventory = "0.1"

# We need this PR (https://github.com/servo/bincode/pull/288) but it's not published yet
#bincode = "1.2"
bincode = { git = "https://github.com/servo/bincode.git", rev="e30e91e3a" }
mopa = "0.2"
itertools = "0.8"

serde-diff = "0.3"

ron = "0.5"
serde_json = "1.0.53"
toml = "0.5.6"
erased-serde = "0.3"

futures = "0.3"
crossbeam-channel = "0.4.2"
rust_decimal = { version = "1.5.0", features = [ "serde-float" ] }

[dev-dependencies]