[package]
name = "demo"
version = "0.1.0"
authors = ["Philip Degarmo <aclysma@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = ">0.30"
imgui = "0.4"
imgui-sdl2 = "0.11.0"
sdl2 = { version = "0.34", features = ["raw-window-handle"] }
image = "0.23.12"
# for https://github.com/gltf-rs/gltf/pull/288
#gltf = "0.15"
gltf = { git = "https://github.com/gltf-rs/gltf.git", rev = "e49aef5ee7b40c2c8f8a50efaed36b97bbb52bd4" }

crossbeam-channel = "0.4.2"

vk-mem = "0.2"

rafx = { path = "../rafx", features = ["assets"] }
shaders = { path = "shaders" }

legion = { version = "0.3.0", default-features = false, features = ["serialize"] }
atelier-assets = { git = "https://github.com/aclysma/atelier-assets", branch = "rafx", features = ["serde_importers", "asset_uuid_macro"] }
futures-lite = "1.3.0"

env_logger = "0.6"

log = "0.4"
glam = "0.8.6"
rand = "0.7.3"
pcg_rand = "0.11.1"

fnv = "1.0"

serde = "1"
serde_bytes = "0.11"
uuid = "0.8"
type-uuid = "0.1"
image2 = { version = "0.11", features = [ "ser" ] }
dashmap = { version = "3.11" }

itertools = "0.8"
bincode = "1.3.1"
mopa = "0.2"
lazy_static = "1"

ron = "0.5"

arrayvec = "0.5"

structopt = "0.3"

puffin-imgui = { version = "0.4.0", optional = true }

tracing = { version = "0.1", optional = true }
tracing-subscriber = { version = "0.2", optional = true }

profiling = "0.1.4"

[features]
default = [
    "sdl2-bundled",
    "sdl2-static-link",
    "profile-with-puffin",
    #"profile-with-optick",
    #"profile-with-tracy",
    #"profile-with-superluminal"
]
sdl2-bundled = ["sdl2/bundled"]
sdl2-static-link = ["sdl2/static-link"]
static-vulkan = ["rafx/static-vulkan"]
profile-with-puffin = [
    "profiling/profile-with-puffin",
    "rafx/profile-with-puffin",
    "puffin-imgui"
]
profile-with-optick = [
    "profiling/profile-with-optick",
    "rafx/profile-with-optick",
]
profile-with-superluminal = [
    "profiling/profile-with-superluminal",
    "rafx/profile-with-superluminal",
]
profile-with-tracy = [
    "profiling/profile-with-tracing",
    "rafx/profile-with-tracing",
    "tracing-subscriber",
    "tracing"
]
profile-with-tracy-memory = [
    "profiling/profile-with-tracing",
    "profile-with-tracy"
]
