[package]
name = "demo"
version = "0.1.0"
authors = ["Philip Degarmo <aclysma@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = ">0.30"
imgui = "0.3"
imgui-sdl2 = "0.9.0"
sdl2 = { version = "0.33", features = ["bundled", "static-link"] }
image = "0.23"
gltf = "0.15"

crossbeam-channel = "0.4.2"

vk-mem = "0.2"

renderer = { path = "../renderer" }
renderer-shell-vulkan-sdl2 = { path = "../renderer-shell-vulkan-sdl2" }
#renderer-base = { path = "../renderer-base" }
#renderer-nodes = { path = "../renderer-nodes" }
#renderer-assets = { path = "../renderer-assets" }
#renderer-resources = { path = "../renderer-resources" }
#renderer-visibility = { path = "../renderer-visibility" }

#renderer-shell-vulkan = { path = "../renderer-shell-vulkan" }

legion = "0.2.4"
atelier-assets = { git = "https://github.com/amethyst/atelier-assets" }

env_logger = "0.6"

log="0.4"
glam = "0.8.6"
rand = "0.7.3"
pcg_rand = "0.11.1"

fnv = "1.0"

serde = "1"
serde_bytes = "0.11"
uuid = "0.8"
type-uuid = "0.1"
image2 = { version = "0.11", features = [ "ser" ] }
inventory = "0.1"
dashmap = { version = "3.11" }

# We need this PR (https://github.com/servo/bincode/pull/288) but it's not published yet
#bincode = "1.2"
bincode = { git = "https://github.com/servo/bincode.git", rev="e30e91e3a" }
mopa = "0.2"

ron = "0.5"

arrayvec = "0.5"

structopt = "0.3"
